version: '3'
services:
    mysql:
        environment:
            - MYSQL_DATABASE=root
            - MYSQL_ROOT_PASSWORD=changeme
            - MYSQL_USER=loguser
            - MYSQL_PASSWORD=loguser
        command:
            - --table_definition_cache=100
            - --performance_schema=0
            - --default-authentication-plugin=mysql_native_password
            - --innodb_use_native_aio=0
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/mysql
        container_name: mysqldb
        image: mysql
        ports:
            - "3306:3306"
    apache:
        volumes:
            - ./apacheconf/apache.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./html:/var/www/html
        container_name: apache
        image: ubu_apache
        depends_on:
            - mysql
        ports:
            - "80:80"